name: 'to_multiplex_map'
version: '1.0.0'
config-version: 2

profile: 'to_multiplex_map'

model-paths: ["models"]

models:
  to_multiplex_map:
    +materialized: table

seeds:
  to_multiplex_map:
    llm_permit_scope:
      +column_types:
        permit_num: varchar
        description_hash: varchar
        construction_type: varchar
        unit_form: varchar
        model: varchar
